name: warpnet_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - opencv
  - scikit-image
  - pillow
  - pandas
  - matplotlib
  - tqdm
  - jupyterlab
  - pytorch
  - torchvision
  - torchaudio
  - ruff
  - kaggle
  - numpy
  - numba
  - scikit-learn
  - pip:
      - kornia
      - transformers
      - datasets
      - evaluate
      - pytesseract
      - tensorboard